id: A4955A6A4
base_file: f713B.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:01:28.407824
  last_modified_at: 2022-05-30 23:01:28.407832
